# Generated by Django 4.2.18 on 2025-01-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон клиента')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес склада')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес склада')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала хранения')),
                ('date_final', models.DateField(blank=True, null=True, verbose_name='Дата окончания хранения')),
                ('reminder_1', models.DateTimeField(editable=False, null=True, verbose_name='Первое напоминание')),
                ('reminder_2', models.DateTimeField(editable=False, null=True, verbose_name='Второе напоминание')),
                ('reminder_3', models.DateTimeField(editable=False, null=True, verbose_name='Третье напоминание')),
                ('reminder_4', models.DateTimeField(editable=False, null=True, verbose_name='Четвертое напоминание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storage.clients', verbose_name='Клиент')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storage.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
