# Generated by Django 4.2.18 on 2025-01-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(choices=[('S', 'Малый (до 1м³)'), ('M', 'Средний (1-5м³)'), ('L', 'Большой (5-10м³)')], max_length=20, verbose_name='Объем')),
                ('address_from', models.TextField(verbose_name='Адрес забора')),
                ('delivery_type', models.CharField(choices=[('PICKUP', 'Самовывоз'), ('DELIVERY', 'Доставка')], max_length=20, verbose_name='Тип доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата окончания хранения')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('reminder_1', models.DateTimeField(editable=False, null=True, verbose_name='Первое напоминание')),
                ('reminder_2', models.DateTimeField(editable=False, null=True, verbose_name='Второе напоминание')),
                ('reminder_3', models.DateTimeField(editable=False, null=True, verbose_name='Третье напоминание')),
                ('reminder_4', models.DateTimeField(editable=False, null=True, verbose_name='Четвертое напоминание')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='StorageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(max_length=10, verbose_name='Номер бокса')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занят')),
            ],
            options={
                'verbose_name': 'бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='StorageBoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SMALL', 'Малый (<1м³)'), ('MEDIUM', 'Средний (1м³-5м³)'), ('LARGE', 'Большой (5м³<)')], max_length=20, verbose_name='Тип бокса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Габариты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип бокса',
                'verbose_name_plural': 'Типы боксов',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clients',
            name='telegram_id',
            field=models.PositiveBigIntegerField(null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(verbose_name='Адрес склада'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='storageboxtype',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_types', to='storage.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='storagebox',
            name='box_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storageboxtype', verbose_name='Тип бокса'),
        ),
        migrations.AddField(
            model_name='storagebox',
            name='current_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_box', to='storage.order', verbose_name='Текущий заказ'),
        ),
        migrations.AddField(
            model_name='storagebox',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storagebox', verbose_name='Бокс'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storage.clients', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterUniqueTogether(
            name='storageboxtype',
            unique_together={('warehouse', 'name')},
        ),
    ]
